crudexample/crudexample/urls.py
from django.contrib import admin
from django.urls import path
from employee import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home),
    path('add',views.add),
    path('show',views.show),
    path('edit/<int:id>',views.edit),
    path('update/<int:id>',views.update),
    path('delete/<int:id>',views.delete)

]

crudexample/employee/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)

    class Meta:
        db_table = "employee"

crudexample/employee/forms.py
from django import forms
from employee.models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

crudexample/employee/views.py
from django.shortcuts import render,redirect
from employee.forms import EmployeeForm
from employee.models import Employee

# Create your views here.
def home(request):
    return render(request,'home.html')

# Code For add_employee
def add(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, 'add.html', {'form': form})

# Code For show_employee
def show(request):
    employees = Employee.objects.all()
    return render(request,'show.html',{'employees':employees})

# Code For edit
def edit(request,id):
    employee = Employee.objects.get(id=id)
    return render(request, 'edit.html' , {'employee':employee})

# Code For Update
def update(request,id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST,instance=employee)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, 'edit.html' , {'employee':employee})
    

# Code For delete
def delete(request,id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")





crudexample/employee/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADD</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" 
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
    <form action="/add" method="POST" class="post-form">
        {% csrf_token %}

        <div class="container">
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <h3>Enter Details</h3>
                    </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee ID : </label>
                <div class="col-sm-4">
                    {{form.eid}}
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Name : </label>
                    <div class="col-sm-4">
                        {{form.ename}}
                    </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Email : </label>
                    <div class="col-sm-4">
                        {{form.eemail}}
                    </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Contact : </label>
                    <div class="col-sm-4">
                        {{form.econtact}}
                    </div>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>

        </div>
    </form>
</body>
</html>

crudexample/employee/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" 
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
    <form method="POST" class="post-form" action="/update/{{employee.id}}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label> 
                <div class="col-sm-4">
                    <h3>Update Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee ID : </label>
                <div class="col-sm-4">
                    <input type="text" name="eid" id="id_eid" value="{{ employee.eid }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Name : </label>
                <div class="col-sm-4">
                    <input type="text" name="ename" id="id_ename" value="{{ employee.ename }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Email : </label>
                <div class="col-sm-4">
                    <input type="text" name="eemail" id="id_eemail" value="{{ employee.eemail }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Contact : </label>
                <div class="col-sm-4">
                    <input type="text" name="econtact" id="id_econtact" value="{{ employee.econtact }}"/>
                </div>
            </div>
            <button type="submit" class="btn btn-success">Update</button>
        </div>
    </form>    
</body>
</html>

crudexample/employee/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" 
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <style>
        .nav-link{
            font-size: 25px;
        }
    </style>
</head>
<body>

    <div class="container text-center mt-5">
        <h1>Welcome To Home Page</h1>
    </div>

    <nav class="navbar navbar-expand-lg">


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#demo">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="demo">

            <ul class="navbar-nav m-auto">

                <li class="nav-item active">
                    <a href="#" class="nav-link">HOME</a>
                </li>

                <li class="nav-item">
                    <a href="/add" class="nav-link">ADD</a>
                </li>

                <li class="nav-item">
                    <a href="/show" class="nav-link">SHOW</a>
                </li>

            </ul>
        </div>
    </nav>

    
    
</body>
</html>

crudexample/employee/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Show</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" 
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
    <div class="container">
        <table class="table table-striped table-bordered table-sm">
            <thead class="thead-dark">
                <tr>
                    <th>Employee ID</th>
                    <th>Employee Name</th>
                    <th>Employee Email</th>
                    <th>Employee Contact</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                    <tr>
                        <td>{{ employee.eid }}</td>
                        <td>{{ employee.ename }}</td>
                        <td>{{ employee.eemail }}</td>
                        <td>{{ employee.econtact }}</td>
                        <td>
                            <a href="/edit/{{ employee.id }}"><span class="fas fa-pencil-alt"></span> Edit</a> | 
                            <a href="/delete/{{ employee.id }}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <center><a href="/add" class="btn btn-primary">Add New Record</a></center>
    </div>
</body>
</html>